FROM node:15.13.0 as static-node-source

FROM google/cloud-sdk

COPY --from=static-node-source /usr/local/bin/ /usr/local/bin/
COPY --from=static-node-source /usr/local/lib/node_modules /usr/local/lib/node_modules

COPY ./  usr/src/app/

WORKDIR /usr/src/app/

RUN npm ci

WORKDIR /usr/src/app/client

RUN npm ci 

WORKDIR /usr/src/app/

CMD npm run client:test
